version: "3.7"

services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    tmpfs:
      - /tmp
      - /var/run/postgresql
    pids_limit: 100
    deploy:
      resources:
        limits:
          cpus: ${POSTGRES_CPU_LIMIT}
          memory: ${POSTGRES_MEMORY_LIMIT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 60s
      timeout: 30s
      retries: 3
    environment:
      # timezone inside container
      - TZ
      # necessary Postgres options/variables
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  mattermost:
    depends_on:
      - postgres
    image: mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    pids_limit: 200
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: ${MATTERMOST_CPU_LIMIT}
          memory: ${MATTERMOST_MEMORY_LIMIT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${HTTPS_PORT}/api/v4/system/ping"]
      interval: 60s
      timeout: 30s
      retries: 3
    environment:
      # timezone inside container
      - TZ
      # necessary Mattermost options/variables (see env.example)
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE
      # necessary for bleve
      - MM_BLEVESETTINGS_INDEXDIR
      # additional settings
      - MM_SERVICESETTINGS_SITEURL
    volumes:
      - ${MATTERMOST_CONFIG_PATH}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw
      - ${MATTERMOST_BLEVE_INDEXES_PATH}:/mattermost/bleve-indexes:rw
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority 
      # (link: https://github.com/mattermost/mattermost-server/issues/13059 and https://github.com/mattermost/docker/issues/34)
      # - ${GITLAB_PKI_CHAIN_PATH}:/etc/ssl/certs/pki_chain.pem:ro

      # Uncomment if using Enterprise Edition with a license
      # - ./volumes/app/mattermost/license:/mattermost/license:rw
      # <or>
      # - ./volumes/app/mattermost/secrets/mattermost-license.txt:/mattermost/config/mattermost-license.txt:ro
    
  nginx:
    depends_on:
      - mattermost
    image: nginx:${NGINX_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    pids_limit: 100
    tmpfs:
      - /var/run
      - /var/log/nginx
    deploy:
      resources:
        limits:
          cpus: ${NGINX_CPU_LIMIT}
          memory: ${NGINX_MEMORY_LIMIT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${HTTP_PORT}/"]
      interval: 60s
      timeout: 30s
      retries: 3
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d:ro
      - ${CERT_PATH}:/etc/nginx/certs/cert.crt:ro
      - ${KEY_PATH}:/etc/nginx/certs/key.key:ro
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
      - ${CALLS_PORT}:8443

networks:
  default:
    name: mattermost
